#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/.zshrc $HOME/.zshrc

rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config/kitty

rm -rf $HOME/.config/i3
ln -s $DOTFILES/i3 $HOME/.config/i3

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.xbindkeysrc
ln -s $DOTFILES/xbindkeys/.xbindkeysrc $HOME/.xbindkeysrc

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.config/nvim/lua/user
ln -s $DOTFILES/user-settings_astrovim $HOME/.config/nvim/lua/user

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

rm -rf $HOME/.phpcs.xml
ln -s $DOTFILES/.phpcs.xml $HOME/.phpcs.xml
