#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.zshrc
ln -s $DOTFILES/zsh/.zshrc $HOME/.zshrc

rm -rf $HOME/.zsh_functions
ln -s $DOTFILES/zsh/.zsh_functions $HOME/.zsh_functions

rm -rf $HOME/.config/alacritty
ln -s $DOTFILES/alacritty $HOME/.config/alacritty

rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/.tmux.conf $HOME/.tmux.conf
