full_text=〉
align=center
color=#FFF
sep_block_width=7

[volume]
command=~/.config/i3blocks/volume/volume
LABEL=♪ 
interval=1
signal=10
#STEP=5%
#MIXER=[determined automatically]
#SCONTROL=[determined automatically]
#NATURAL_MAPPING=0

[disk]
command=~/.config/i3blocks/disk/disk
LABEL=DISK: 
#DIR=$HOME
#ALERT_LOW=10
interval=30

[memory]
command=~/.config/i3blocks/memory/memory
label=MEM: 
interval=30

[cpu_usage]
command=~/.config/i3blocks/cpu_usage/cpu_usage
interval=10
LABEL=CPU 
#T_WARN=50
#T_CRIT=80
#DECIMALS=2
COLOR_NORMAL=#FFF
COLOR_WARN=#FFFC00
COLOR_CRIT=#FF0000

[calendar]
command=~/.config/i3blocks/calendar/calendar
interval=1
LABEL=  
DATEFMT=+%a %m/%d/%Y | %I:%M:%S
# SHORTFMT=+%H:%M:%S
HEIGHT=180
WIDTH=220

[battery2]
command=~/.config/i3blocks/battery2/battery2
markup=pango
interval=30
min_width=OOOOOOOO
